/*
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.lakefs.clients.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.lakefs.clients.api.model.GCUncommittedPagination;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GarbageCollectionPrepareUncommittedResponse
 */
public class GarbageCollectionPrepareUncommittedResponseTest {
    private final GarbageCollectionPrepareUncommittedResponse model = new GarbageCollectionPrepareUncommittedResponse();

    /**
     * Model tests for GarbageCollectionPrepareUncommittedResponse
     */
    @Test
    public void testGarbageCollectionPrepareUncommittedResponse() {
        // TODO: test GarbageCollectionPrepareUncommittedResponse
    }

    /**
     * Test the property 'runId'
     */
    @Test
    public void runIdTest() {
        // TODO: test runId
    }

    /**
     * Test the property 'gcUncommittedLocation'
     */
    @Test
    public void gcUncommittedLocationTest() {
        // TODO: test gcUncommittedLocation
    }

    /**
     * Test the property 'pagination'
     */
    @Test
    public void paginationTest() {
        // TODO: test pagination
    }

}
