run:
  tests: false
  timeout: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - err113
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  mnd:
    ignored-files:
      - 'pkg/actions/lua/.*'

issues:
  exclude-dirs:
    - pkg/metastore/hive/gen-go
