version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - err113
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - mnd
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    mnd:
      ignored-files:
        - pkg/actions/lua/.*
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
        - -QF1001 # Apply De Morgan’s law
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - pkg/metastore/hive/gen-go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - pkg/metastore/hive/gen-go
      - third_party$
      - builtin$
      - examples$
