project_name: lakeFS
before:
  hooks:
    - go mod download
    - make gen VERSION="{{.Version}}"
release:
  disable: false
  prerelease: true
  ids: [default]
builds:
- id: lakefs
  main: ./cmd/lakefs
  binary: lakefs
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X github.com/treeverse/lakefs/pkg/version.Version={{.Version}}
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - linux
  - windows
- id: lakectl
  main: ./cmd/lakectl
  binary: lakectl
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X github.com/treeverse/lakefs/pkg/version.Version={{.Version}}
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - linux
  - windows
archives:
- id: default
  rlcp: true
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{- title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}'
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - src: 'delta/artifacts/delta-{{ tolower .Os }}-{{ tolower .Arch }}/delta_diff*'
      strip_parent: true
  builds:
   - lakefs
   - lakectl
- id: lakectl
  rlcp: true
  format_overrides:
    - goos: windows
      format: zip
  format: binary
  name_template: '{{- title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}/lakectl'
  builds:
   - lakectl
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
blobs:
- provider: s3
  region: us-east-1
  bucket: treeverse-clients-us-east
  folder: "lakectl/{{.Version}}"
  ids:
   - lakectl
brews:
- name: lakefs
  homepage: https://github.com/treeverse/lakefs 
  description: "lakeFS is an open-source tool that transforms your object storage into a Git-like repository. It enables you to manage your data lake the way you manage your code."
  ids:
    - default
  tap:
    owner: treeverse
    name: homebrew-lakefs
    token: "{{ .Env.TAP_GITHUB_TOKEN }}"
