/*
 * lakeFS API
 *
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: services@treeverse.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GarbageCollectionRule {
    #[serde(rename = "branch_id")]
    pub branch_id: String,
    #[serde(rename = "retention_days")]
    pub retention_days: i32,
}

impl GarbageCollectionRule {
    pub fn new(branch_id: String, retention_days: i32) -> GarbageCollectionRule {
        GarbageCollectionRule {
            branch_id,
            retention_days,
        }
    }
}

