/*
 * lakeFS API
 *
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: services@treeverse.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct License {
    /// The license JWT token
    #[serde(rename = "token")]
    pub token: String,
}

impl License {
    pub fn new(token: String) -> License {
        License {
            token,
        }
    }
}

