theme: jekyll-theme-slate
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - _config.yml
  - build
  - build-package.sh
  - dist
  - lakefs_sdk
  - lakefs_sdk.egg-info
  - requirements.txt
  - setup.cfg
  - setup.py
  - test
  - test-requirements.txt
  - tox.ini
