spark:
  target: main
  outputs:

    main:
      method: thrift
      type: spark
      schema: dbt_main
      host: spark-thrift
      port: 10000
      user: admin
      password: admin
      connect_retries: 5
      threads: 4
      connect_timeout: 60

      branch:
        method: thrift
        type: spark
        schema: <BRANCH-SCHEMA>
        user: admin
        password: admin
        host: spark-thrift
        port: 10000
        connect_retries: 5
        connect_timeout: 60

trino:
  target: main
  outputs:

    main:
      type: trino
      method: none
      user: trino

      database: s3 # equal to presto trino catalog
      host: trino
      port: 8080
      schema: test
      threads: 1

    branch:
      type: trino
      method: none
      user: trino
      database: s3 # equal to presto trino catalog
      host: trino
      port: 8080
      schema: <BRANCH-SCHEMA>
      threads: 1
