DROP TABLE IF EXISTS credentials;
DROP TABLE IF EXISTS group_policies;
DROP TABLE IF EXISTS user_policies;
DROP TABLE IF EXISTS user_groups;
DROP TABLE IF EXISTS policies;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS users;
