version: '3'
services:
  lakefs:
    image: "lakefs"
    #image: "${REPO:-treeverse}/lakefs:${TAG:-dev}"
    volumes: 
      - lakefs-app:/app:ro
    environment:
      - LAKEFS_AUTH_ENCRYPT_SECRET_KEY=some random secret string
      - LAKEFS_DATABASE_TYPE=${LAKEFS_DATABASE_TYPE:-local}
      - LAKEFS_BLOCKSTORE_TYPE=${LAKEFS_BLOCKSTORE_TYPE:-local}
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - LAKEFS_LOGGING_LEVEL=DEBUG
      - LAKEFS_BLOCKSTORE_GS_CREDENTIALS_JSON
      - LAKEFS_STATS_ENABLED
      - LAKEFS_BLOCKSTORE_AZURE_STORAGE_ACCOUNT
      - LAKEFS_BLOCKSTORE_AZURE_STORAGE_ACCESS_KEY
      - ACTIONS_VAR=this_is_actions_var

  esti:
    image: "golang:1.19.2-alpine"
    links:
      - lakefs:s3.local.lakefs.io
      - lakefs:testmultipartupload.s3.local.lakefs.io
      - lakefs:testdeleteobjects.s3.local.lakefs.io
      - lakefs:testmigrate-testpremigratemultipart.s3.local.lakefs.io
      - lakefs:migrate.s3.local.lakefs.io
    environment:
      - CGO_ENABLED=0
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION=us-east-1
      - ESTI_TEST_DATA_ACCESS
      - ESTI_STORAGE_NAMESPACE
      - ESTI_BLOCKSTORE_TYPE
      - ESTI_AWS_ACCESS_KEY_ID
      - ESTI_SETUP_LAKEFS
      - ESTI_AWS_SECRET_ACCESS_KEY
      - ESTI_ENDPOINT_URL=http://lakefs:8000
      - ESTI_LAKECTL_DIR=/app
      - ESTI_GOTEST_FLAGS
      - ESTI_FLAGS
      - ESTI_FORCE_PATH_STYLE
    working_dir: /lakefs
    command:
      - /bin/sh
      - -c
      - |
        apk add --no-cache util-linux
        go test -v $ESTI_GOTEST_FLAGS ./esti --system-tests $ESTI_FLAGS
    volumes:
      - lakefs-code:/lakefs
      - lakefs-app:/app:ro 

volumes:
  lakefs-code:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${LAKEFS_ROOT:-.}
  lakefs-app:

