name: Bug Report v2
description: File a bug report
title: "[Bug]: "
labels: ["bug", "contributor"]
body:
  - type: markdown
    attributes:
      value: |
        ## Hello Axolotl!
        **Thank you for contributing to the lakeFS project.**
        We appreciate the time you invest in filing a bug report and created this template to help make this process easier.
        It's really important to have all the information and context, to ensure we can properly address your issue. 
        Please use the following references to fill out the bug report.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      value: |  
        Current Behavior:
        What actually happened, including error codes if applies.
                
        Expected Behavior:
        How you expected thing to work.
                
        Steps to Reproduce
        1.
        2.
        3.
    validations:
      required: true
  - type: input
    id: lakefs_version
    attributes:
      label: lakeFS Version
      description: What version of lakeFS are you running?
  - type: input
    id: deployment
    attributes:
      label: Deplyoment
      description: lakeFS deployment type
      placeholder: ex. AWS ECS, Docker or Kubernetes, helm-chart, local
    validations:
      required: true
  - type: input
    id: Clients
    attributes:
      label: Affected Clients
      description: If applicable provide lakeFS client and version that was used
      placeholder: ex. hadoop-lakefs 0.1.9, python lakefs-client 0.89.0
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs output
      description: Please copy and paste any relevant log output (lakeFS, clients, ecosystem). Make sure to scrub anything confidential! These will typically be near strings such as `secret`, `access` or `AKIA`
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/treeverse/lakeFS/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
