"""
    lakeFS API

    lakeFS HTTP API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: services@treeverse.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lakefs_client
from lakefs_client.model.group_creation import GroupCreation


class TestGroupCreation(unittest.TestCase):
    """GroupCreation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupCreation(self):
        """Test GroupCreation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GroupCreation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
