"""
    lakeFS API

    lakeFS HTTP API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lakefs
from lakefs.model.pagination import Pagination
from lakefs.model.repository import Repository
globals()['Pagination'] = Pagination
globals()['Repository'] = Repository
from lakefs.model.repository_list import RepositoryList


class TestRepositoryList(unittest.TestCase):
    """RepositoryList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepositoryList(self):
        """Test RepositoryList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RepositoryList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
