BEGIN;
ALTER TABLE kv_staging_p0 RENAME TO graveler_staging_kv_p0;
ALTER TABLE kv_staging_p1 RENAME TO graveler_staging_kv_p1;
ALTER TABLE kv_staging_p2 RENAME TO graveler_staging_kv_p2;
ALTER TABLE kv_staging_p3 RENAME TO graveler_staging_kv_p3;
ALTER TABLE kv_staging_p4 RENAME TO graveler_staging_kv_p4;
ALTER TABLE kv_staging_p5 RENAME TO graveler_staging_kv_p5;
ALTER TABLE kv_staging_p6 RENAME TO graveler_staging_kv_p6;
ALTER TABLE kv_staging_p7 RENAME TO graveler_staging_kv_p7;
ALTER TABLE kv_staging_p8 RENAME TO graveler_staging_kv_p8;
ALTER TABLE kv_staging_p9 RENAME TO graveler_staging_kv_p9;
COMMIT;
