spark:
  target: demo
  outputs:
    main:
      method: thrift
      type: spark
      schema: new_spark_main
      host: spark
      port: 10000
      user: admin
      password: admin
      connect_retries: 5
      connect_timeout: 60

    demo:
      method: thrift
      type: spark
      schema: demo
      host: spark
      port: 10000
      user: admin
      password: admin
      connect_retries: 5
      connect_timeout: 60

trino:
  target: branch2
  outputs:

    branch2:
      type: trino
      method: none
      user: guyhardonag
      # password: password
      database: s3 # equal to presto trino catalog
      host: localhost
      port: 8080
      schema: new_branch2 #default # eqivilant to schema
      threads: 1

    main:
      type: trino
      method: none
      user: guyhardonag
      # password: password
      database: s3 # equal to presto trino catalog
      host: localhost
      port: 8080
      schema: new_branch1 #default # eqivilant to schema
      threads: 1
