/* tslint:disable */
/* eslint-disable */
/**
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HookRun
 */
export interface HookRun {
    /**
     * 
     * @type {string}
     * @memberof HookRun
     */
    hookRunId: string;
    /**
     * 
     * @type {string}
     * @memberof HookRun
     */
    action: string;
    /**
     * 
     * @type {string}
     * @memberof HookRun
     */
    hookId: string;
    /**
     * 
     * @type {Date}
     * @memberof HookRun
     */
    startTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof HookRun
     */
    endTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof HookRun
     */
    status: HookRunStatus;
}

/**
* @export
* @enum {string}
*/
export enum HookRunStatus {
    failed = 'failed',
    completed = 'completed'
}


/**
 * Check if a given object implements the HookRun interface.
 */
export function instanceOfHookRun(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "hookRunId" in value;
    isInstance = isInstance && "action" in value;
    isInstance = isInstance && "hookId" in value;
    isInstance = isInstance && "startTime" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function HookRunFromJSON(json: any): HookRun {
    return HookRunFromJSONTyped(json, false);
}

export function HookRunFromJSONTyped(json: any, ignoreDiscriminator: boolean): HookRun {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hookRunId': json['hook_run_id'],
        'action': json['action'],
        'hookId': json['hook_id'],
        'startTime': (new Date(json['start_time'])),
        'endTime': !exists(json, 'end_time') ? undefined : (new Date(json['end_time'])),
        'status': json['status'],
    };
}

export function HookRunToJSON(value?: HookRun | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hook_run_id': value.hookRunId,
        'action': value.action,
        'hook_id': value.hookId,
        'start_time': (value.startTime.toISOString()),
        'end_time': value.endTime === undefined ? undefined : (value.endTime.toISOString()),
        'status': value.status,
    };
}

