/* tslint:disable */
/* eslint-disable */
/**
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MergeResult } from './MergeResult';
import {
    MergeResultFromJSON,
    MergeResultFromJSONTyped,
    MergeResultToJSON,
} from './MergeResult';

/**
 * 
 * @export
 * @interface MergeAsyncStatus
 */
export interface MergeAsyncStatus {
    /**
     * the id of the async task
     * @type {string}
     * @memberof MergeAsyncStatus
     */
    taskId: string;
    /**
     * true if the task has completed (either successfully or with an error)
     * @type {boolean}
     * @memberof MergeAsyncStatus
     */
    completed: boolean;
    /**
     * last time the task status was updated
     * @type {Date}
     * @memberof MergeAsyncStatus
     */
    updateTime: Date;
    /**
     * 
     * @type {Error}
     * @memberof MergeAsyncStatus
     */
    error?: Error;
    /**
     * an http status code that correlates with the underlying error if exists
     * @type {number}
     * @memberof MergeAsyncStatus
     */
    statusCode?: number;
    /**
     * 
     * @type {MergeResult}
     * @memberof MergeAsyncStatus
     */
    result?: MergeResult;
}

/**
 * Check if a given object implements the MergeAsyncStatus interface.
 */
export function instanceOfMergeAsyncStatus(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "taskId" in value;
    isInstance = isInstance && "completed" in value;
    isInstance = isInstance && "updateTime" in value;

    return isInstance;
}

export function MergeAsyncStatusFromJSON(json: any): MergeAsyncStatus {
    return MergeAsyncStatusFromJSONTyped(json, false);
}

export function MergeAsyncStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): MergeAsyncStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'taskId': json['task_id'],
        'completed': json['completed'],
        'updateTime': (new Date(json['update_time'])),
        'error': !exists(json, 'error') ? undefined : json['error'],
        'statusCode': !exists(json, 'status_code') ? undefined : json['status_code'],
        'result': !exists(json, 'result') ? undefined : MergeResultFromJSON(json['result']),
    };
}

export function MergeAsyncStatusToJSON(value?: MergeAsyncStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'task_id': value.taskId,
        'completed': value.completed,
        'update_time': (value.updateTime.toISOString()),
        'error': value.error,
        'status_code': value.statusCode,
        'result': MergeResultToJSON(value.result),
    };
}

