/* tslint:disable */
/* eslint-disable */
/**
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrepareGCUncommittedResponse
 */
export interface PrepareGCUncommittedResponse {
    /**
     * 
     * @type {string}
     * @memberof PrepareGCUncommittedResponse
     */
    runId: string;
    /**
     * location of uncommitted information data
     * @type {string}
     * @memberof PrepareGCUncommittedResponse
     */
    gcUncommittedLocation: string;
    /**
     * 
     * @type {string}
     * @memberof PrepareGCUncommittedResponse
     */
    continuationToken?: string;
}

/**
 * Check if a given object implements the PrepareGCUncommittedResponse interface.
 */
export function instanceOfPrepareGCUncommittedResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "runId" in value;
    isInstance = isInstance && "gcUncommittedLocation" in value;

    return isInstance;
}

export function PrepareGCUncommittedResponseFromJSON(json: any): PrepareGCUncommittedResponse {
    return PrepareGCUncommittedResponseFromJSONTyped(json, false);
}

export function PrepareGCUncommittedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrepareGCUncommittedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'runId': json['run_id'],
        'gcUncommittedLocation': json['gc_uncommitted_location'],
        'continuationToken': !exists(json, 'continuation_token') ? undefined : json['continuation_token'],
    };
}

export function PrepareGCUncommittedResponseToJSON(value?: PrepareGCUncommittedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'run_id': value.runId,
        'gc_uncommitted_location': value.gcUncommittedLocation,
        'continuation_token': value.continuationToken,
    };
}

