/* tslint:disable */
/* eslint-disable */
/**
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PresignMultipartUpload
 */
export interface PresignMultipartUpload {
    /**
     * 
     * @type {string}
     * @memberof PresignMultipartUpload
     */
    uploadId: string;
    /**
     * 
     * @type {string}
     * @memberof PresignMultipartUpload
     */
    physicalAddress: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PresignMultipartUpload
     */
    presignedUrls?: Array<string>;
}

/**
 * Check if a given object implements the PresignMultipartUpload interface.
 */
export function instanceOfPresignMultipartUpload(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "uploadId" in value;
    isInstance = isInstance && "physicalAddress" in value;

    return isInstance;
}

export function PresignMultipartUploadFromJSON(json: any): PresignMultipartUpload {
    return PresignMultipartUploadFromJSONTyped(json, false);
}

export function PresignMultipartUploadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PresignMultipartUpload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uploadId': json['upload_id'],
        'physicalAddress': json['physical_address'],
        'presignedUrls': !exists(json, 'presigned_urls') ? undefined : json['presigned_urls'],
    };
}

export function PresignMultipartUploadToJSON(value?: PresignMultipartUpload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'upload_id': value.uploadId,
        'physical_address': value.physicalAddress,
        'presigned_urls': value.presignedUrls,
    };
}

