/* tslint:disable */
/* eslint-disable */
/**
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LoginConfig } from './LoginConfig';
import {
    LoginConfigFromJSON,
    LoginConfigFromJSONTyped,
    LoginConfigToJSON,
} from './LoginConfig';

/**
 * 
 * @export
 * @interface SetupState
 */
export interface SetupState {
    /**
     * 
     * @type {string}
     * @memberof SetupState
     */
    state?: SetupStateState;
    /**
     * true if the comm prefs are missing.
     * @type {boolean}
     * @memberof SetupState
     */
    commPrefsMissing?: boolean;
    /**
     * 
     * @type {LoginConfig}
     * @memberof SetupState
     */
    loginConfig?: LoginConfig;
}

/**
* @export
* @enum {string}
*/
export enum SetupStateState {
    initialized = 'initialized',
    not_initialized = 'not_initialized'
}


/**
 * Check if a given object implements the SetupState interface.
 */
export function instanceOfSetupState(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SetupStateFromJSON(json: any): SetupState {
    return SetupStateFromJSONTyped(json, false);
}

export function SetupStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetupState {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'state': !exists(json, 'state') ? undefined : json['state'],
        'commPrefsMissing': !exists(json, 'comm_prefs_missing') ? undefined : json['comm_prefs_missing'],
        'loginConfig': !exists(json, 'login_config') ? undefined : LoginConfigFromJSON(json['login_config']),
    };
}

export function SetupStateToJSON(value?: SetupState | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'state': value.state,
        'comm_prefs_missing': value.commPrefsMissing,
        'login_config': LoginConfigToJSON(value.loginConfig),
    };
}

