/* tslint:disable */
/* eslint-disable */
/**
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadPart
 */
export interface UploadPart {
    /**
     * 
     * @type {number}
     * @memberof UploadPart
     */
    partNumber: number;
    /**
     * 
     * @type {string}
     * @memberof UploadPart
     */
    etag: string;
}

/**
 * Check if a given object implements the UploadPart interface.
 */
export function instanceOfUploadPart(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "partNumber" in value;
    isInstance = isInstance && "etag" in value;

    return isInstance;
}

export function UploadPartFromJSON(json: any): UploadPart {
    return UploadPartFromJSONTyped(json, false);
}

export function UploadPartFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadPart {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'partNumber': json['part_number'],
        'etag': json['etag'],
    };
}

export function UploadPartToJSON(value?: UploadPart | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'part_number': value.partNumber,
        'etag': value.etag,
    };
}

