/* tslint:disable */
/* eslint-disable */
/**
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserCreation
 */
export interface UserCreation {
    /**
     * a unique identifier for the user.
     * @type {string}
     * @memberof UserCreation
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserCreation
     */
    inviteUser?: boolean;
}

/**
 * Check if a given object implements the UserCreation interface.
 */
export function instanceOfUserCreation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function UserCreationFromJSON(json: any): UserCreation {
    return UserCreationFromJSONTyped(json, false);
}

export function UserCreationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCreation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'inviteUser': !exists(json, 'invite_user') ? undefined : json['invite_user'],
    };
}

export function UserCreationToJSON(value?: UserCreation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'invite_user': value.inviteUser,
    };
}

