/**
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: services@treeverse.io
 * Generated by OpenAPI Generator (https://openapi-generator.tech)
 *
 * Do not edit the class manually.
 */

import { InternalApi } from '../../src/apis/InternalApi';

describe('InternalApi', () => {
  let api: InternalApi;

  beforeEach(() => {
    api = new InternalApi();
  });

  describe('createBranchProtectionRule', () => {
    it('should create branch protection rule', async () => {
      // TODO: Implement test
      expect(api).toBeDefined();
    });
  });

  describe('deleteBranchProtectionRule', () => {
    it('should delete branch protection rule', async () => {
      // TODO: Implement test
      expect(api).toBeDefined();
    });
  });

  describe('getBranchProtectionRules', () => {
    it('should get branch protection rules', async () => {
      // TODO: Implement test
      expect(api).toBeDefined();
    });
  });

  describe('getSetupState', () => {
    it('should get setup state', async () => {
      // TODO: Implement test
      expect(api).toBeDefined();
    });
  });

  describe('postStatsEvents', () => {
    it('should post stats events', async () => {
      // TODO: Implement test
      expect(api).toBeDefined();
    });
  });

  describe('setup', () => {
    it('should perform setup', async () => {
      // TODO: Implement test
      expect(api).toBeDefined();
    });
  });

  describe('setGarbageCollectionRules', () => {
    it('should set garbage collection rules', async () => {
      // TODO: Implement test
      expect(api).toBeDefined();
    });
  });

  describe('getGarbageCollectionRules', () => {
    it('should get garbage collection rules', async () => {
      // TODO: Implement test
      expect(api).toBeDefined();
    });
  });

  describe('prepareGarbageCollectionCommits', () => {
    it('should prepare garbage collection commits', async () => {
      // TODO: Implement test
      expect(api).toBeDefined();
    });
  });

  describe('prepareGarbageCollectionUncommitted', () => {
    it('should prepare garbage collection uncommitted', async () => {
      // TODO: Implement test
      expect(api).toBeDefined();
    });
  });

  describe('createSymlinkFile', () => {
    it('should create symlink file', async () => {
      // TODO: Implement test
      expect(api).toBeDefined();
    });
  });
});
