// Code generated by github.com/treeverse/lakefs/tools/wrapgen DO NOT EDIT.

package auth

import (
	"context"
	"time"

	"github.com/treeverse/lakefs/pkg/auth/crypt"
	"github.com/treeverse/lakefs/pkg/auth/model"
)

type MonitoredServiceAndInviter struct {
	Wrapped ServiceAndInviter
	Observe func(operation string, duration time.Duration, success bool)
}

func (w *MonitoredServiceAndInviter) IsAdvancedAuth() bool           { return w.Wrapped.IsAdvancedAuth() }
func (w *MonitoredServiceAndInviter) SecretStore() crypt.SecretStore { return w.Wrapped.SecretStore() }
func (w *MonitoredServiceAndInviter) Cache() Cache                   { return w.Wrapped.Cache() }
func (w *MonitoredServiceAndInviter) CreateUser(ctx context.Context, user *model.User) (string, error) {
	const op = "create_user"
	start := time.Now()

	r0, r1 := w.Wrapped.CreateUser(ctx, user)
	w.Observe(op, time.Since(start), r1 == nil)
	return r0, r1
}
func (w *MonitoredServiceAndInviter) DeleteUser(ctx context.Context, username string) error {
	const op = "delete_user"
	start := time.Now()

	r0 := w.Wrapped.DeleteUser(ctx, username)
	w.Observe(op, time.Since(start), r0 == nil)
	return r0
}
func (w *MonitoredServiceAndInviter) GetUserByID(ctx context.Context, userID string) (*model.User, error) {
	const op = "get_user_by_id"
	start := time.Now()

	r0, r1 := w.Wrapped.GetUserByID(ctx, userID)
	w.Observe(op, time.Since(start), r1 == nil)
	return r0, r1
}
func (w *MonitoredServiceAndInviter) GetUser(ctx context.Context, username string) (*model.User, error) {
	const op = "get_user"
	start := time.Now()

	r0, r1 := w.Wrapped.GetUser(ctx, username)
	w.Observe(op, time.Since(start), r1 == nil)
	return r0, r1
}
func (w *MonitoredServiceAndInviter) GetUserByExternalID(ctx context.Context, externalID string) (*model.User, error) {
	const op = "get_user_by_external_id"
	start := time.Now()

	r0, r1 := w.Wrapped.GetUserByExternalID(ctx, externalID)
	w.Observe(op, time.Since(start), r1 == nil)
	return r0, r1
}
func (w *MonitoredServiceAndInviter) GetUserByEmail(ctx context.Context, email string) (*model.User, error) {
	const op = "get_user_by_email"
	start := time.Now()

	r0, r1 := w.Wrapped.GetUserByEmail(ctx, email)
	w.Observe(op, time.Since(start), r1 == nil)
	return r0, r1
}
func (w *MonitoredServiceAndInviter) ListUsers(ctx context.Context, params *model.PaginationParams) ([]*model.User, *model.Paginator, error) {
	const op = "list_users"
	start := time.Now()

	r0, r1, r2 := w.Wrapped.ListUsers(ctx, params)
	w.Observe(op, time.Since(start), r2 == nil)
	return r0, r1, r2
}
func (w *MonitoredServiceAndInviter) UpdateUserFriendlyName(ctx context.Context, userID string, friendlyName string) error {
	const op = "update_user_friendly_name"
	start := time.Now()

	r0 := w.Wrapped.UpdateUserFriendlyName(ctx, userID, friendlyName)
	w.Observe(op, time.Since(start), r0 == nil)
	return r0
}
func (w *MonitoredServiceAndInviter) CreateGroup(ctx context.Context, group *model.Group) (*model.Group, error) {
	const op = "create_group"
	start := time.Now()

	r0, r1 := w.Wrapped.CreateGroup(ctx, group)
	w.Observe(op, time.Since(start), r1 == nil)
	return r0, r1
}
func (w *MonitoredServiceAndInviter) DeleteGroup(ctx context.Context, groupID string) error {
	const op = "delete_group"
	start := time.Now()

	r0 := w.Wrapped.DeleteGroup(ctx, groupID)
	w.Observe(op, time.Since(start), r0 == nil)
	return r0
}
func (w *MonitoredServiceAndInviter) GetGroup(ctx context.Context, groupID string) (*model.Group, error) {
	const op = "get_group"
	start := time.Now()

	r0, r1 := w.Wrapped.GetGroup(ctx, groupID)
	w.Observe(op, time.Since(start), r1 == nil)
	return r0, r1
}
func (w *MonitoredServiceAndInviter) ListGroups(ctx context.Context, params *model.PaginationParams) ([]*model.Group, *model.Paginator, error) {
	const op = "list_groups"
	start := time.Now()

	r0, r1, r2 := w.Wrapped.ListGroups(ctx, params)
	w.Observe(op, time.Since(start), r2 == nil)
	return r0, r1, r2
}
func (w *MonitoredServiceAndInviter) AddUserToGroup(ctx context.Context, username string, groupID string) error {
	const op = "add_user_to_group"
	start := time.Now()

	r0 := w.Wrapped.AddUserToGroup(ctx, username, groupID)
	w.Observe(op, time.Since(start), r0 == nil)
	return r0
}
func (w *MonitoredServiceAndInviter) RemoveUserFromGroup(ctx context.Context, username string, groupID string) error {
	const op = "remove_user_from_group"
	start := time.Now()

	r0 := w.Wrapped.RemoveUserFromGroup(ctx, username, groupID)
	w.Observe(op, time.Since(start), r0 == nil)
	return r0
}
func (w *MonitoredServiceAndInviter) ListUserGroups(ctx context.Context, username string, params *model.PaginationParams) ([]*model.Group, *model.Paginator, error) {
	const op = "list_user_groups"
	start := time.Now()

	r0, r1, r2 := w.Wrapped.ListUserGroups(ctx, username, params)
	w.Observe(op, time.Since(start), r2 == nil)
	return r0, r1, r2
}
func (w *MonitoredServiceAndInviter) ListGroupUsers(ctx context.Context, groupID string, params *model.PaginationParams) ([]*model.User, *model.Paginator, error) {
	const op = "list_group_users"
	start := time.Now()

	r0, r1, r2 := w.Wrapped.ListGroupUsers(ctx, groupID, params)
	w.Observe(op, time.Since(start), r2 == nil)
	return r0, r1, r2
}
func (w *MonitoredServiceAndInviter) WritePolicy(ctx context.Context, policy *model.Policy, update bool) error {
	const op = "write_policy"
	start := time.Now()

	r0 := w.Wrapped.WritePolicy(ctx, policy, update)
	w.Observe(op, time.Since(start), r0 == nil)
	return r0
}
func (w *MonitoredServiceAndInviter) GetPolicy(ctx context.Context, policyDisplayName string) (*model.Policy, error) {
	const op = "get_policy"
	start := time.Now()

	r0, r1 := w.Wrapped.GetPolicy(ctx, policyDisplayName)
	w.Observe(op, time.Since(start), r1 == nil)
	return r0, r1
}
func (w *MonitoredServiceAndInviter) DeletePolicy(ctx context.Context, policyDisplayName string) error {
	const op = "delete_policy"
	start := time.Now()

	r0 := w.Wrapped.DeletePolicy(ctx, policyDisplayName)
	w.Observe(op, time.Since(start), r0 == nil)
	return r0
}
func (w *MonitoredServiceAndInviter) ListPolicies(ctx context.Context, params *model.PaginationParams) ([]*model.Policy, *model.Paginator, error) {
	const op = "list_policies"
	start := time.Now()

	r0, r1, r2 := w.Wrapped.ListPolicies(ctx, params)
	w.Observe(op, time.Since(start), r2 == nil)
	return r0, r1, r2
}
func (w *MonitoredServiceAndInviter) AddCredentials(ctx context.Context, username string, accessKeyID string, secretAccessKey string) (*model.Credential, error) {
	const op = "add_credentials"
	start := time.Now()

	r0, r1 := w.Wrapped.AddCredentials(ctx, username, accessKeyID, secretAccessKey)
	w.Observe(op, time.Since(start), r1 == nil)
	return r0, r1
}
func (w *MonitoredServiceAndInviter) DeleteCredentials(ctx context.Context, username string, accessKeyID string) error {
	const op = "delete_credentials"
	start := time.Now()

	r0 := w.Wrapped.DeleteCredentials(ctx, username, accessKeyID)
	w.Observe(op, time.Since(start), r0 == nil)
	return r0
}
func (w *MonitoredServiceAndInviter) GetCredentialsForUser(ctx context.Context, username string, accessKeyID string) (*model.Credential, error) {
	const op = "get_credentials_for_user"
	start := time.Now()

	r0, r1 := w.Wrapped.GetCredentialsForUser(ctx, username, accessKeyID)
	w.Observe(op, time.Since(start), r1 == nil)
	return r0, r1
}
func (w *MonitoredServiceAndInviter) GetCredentials(ctx context.Context, accessKeyID string) (*model.Credential, error) {
	const op = "get_credentials"
	start := time.Now()

	r0, r1 := w.Wrapped.GetCredentials(ctx, accessKeyID)
	w.Observe(op, time.Since(start), r1 == nil)
	return r0, r1
}
func (w *MonitoredServiceAndInviter) ListUserCredentials(ctx context.Context, username string, params *model.PaginationParams) ([]*model.Credential, *model.Paginator, error) {
	const op = "list_user_credentials"
	start := time.Now()

	r0, r1, r2 := w.Wrapped.ListUserCredentials(ctx, username, params)
	w.Observe(op, time.Since(start), r2 == nil)
	return r0, r1, r2
}
func (w *MonitoredServiceAndInviter) AttachPolicyToUser(ctx context.Context, policyDisplayName string, username string) error {
	const op = "attach_policy_to_user"
	start := time.Now()

	r0 := w.Wrapped.AttachPolicyToUser(ctx, policyDisplayName, username)
	w.Observe(op, time.Since(start), r0 == nil)
	return r0
}
func (w *MonitoredServiceAndInviter) DetachPolicyFromUser(ctx context.Context, policyDisplayName string, username string) error {
	const op = "detach_policy_from_user"
	start := time.Now()

	r0 := w.Wrapped.DetachPolicyFromUser(ctx, policyDisplayName, username)
	w.Observe(op, time.Since(start), r0 == nil)
	return r0
}
func (w *MonitoredServiceAndInviter) ListUserPolicies(ctx context.Context, username string, params *model.PaginationParams) ([]*model.Policy, *model.Paginator, error) {
	const op = "list_user_policies"
	start := time.Now()

	r0, r1, r2 := w.Wrapped.ListUserPolicies(ctx, username, params)
	w.Observe(op, time.Since(start), r2 == nil)
	return r0, r1, r2
}
func (w *MonitoredServiceAndInviter) ListEffectivePolicies(ctx context.Context, username string, params *model.PaginationParams) ([]*model.Policy, *model.Paginator, error) {
	const op = "list_effective_policies"
	start := time.Now()

	r0, r1, r2 := w.Wrapped.ListEffectivePolicies(ctx, username, params)
	w.Observe(op, time.Since(start), r2 == nil)
	return r0, r1, r2
}
func (w *MonitoredServiceAndInviter) AttachPolicyToGroup(ctx context.Context, policyDisplayName string, groupID string) error {
	const op = "attach_policy_to_group"
	start := time.Now()

	r0 := w.Wrapped.AttachPolicyToGroup(ctx, policyDisplayName, groupID)
	w.Observe(op, time.Since(start), r0 == nil)
	return r0
}
func (w *MonitoredServiceAndInviter) DetachPolicyFromGroup(ctx context.Context, policyDisplayName string, groupID string) error {
	const op = "detach_policy_from_group"
	start := time.Now()

	r0 := w.Wrapped.DetachPolicyFromGroup(ctx, policyDisplayName, groupID)
	w.Observe(op, time.Since(start), r0 == nil)
	return r0
}
func (w *MonitoredServiceAndInviter) ListGroupPolicies(ctx context.Context, groupID string, params *model.PaginationParams) ([]*model.Policy, *model.Paginator, error) {
	const op = "list_group_policies"
	start := time.Now()

	r0, r1, r2 := w.Wrapped.ListGroupPolicies(ctx, groupID, params)
	w.Observe(op, time.Since(start), r2 == nil)
	return r0, r1, r2
}
func (w *MonitoredServiceAndInviter) ClaimTokenIDOnce(ctx context.Context, tokenID string, expiresAt int64) error {
	const op = "claim_token_id_once"
	start := time.Now()

	r0 := w.Wrapped.ClaimTokenIDOnce(ctx, tokenID, expiresAt)
	w.Observe(op, time.Since(start), r0 == nil)
	return r0
}
func (w *MonitoredServiceAndInviter) IsExternalPrincipalsEnabled(ctx context.Context) bool {
	return w.Wrapped.IsExternalPrincipalsEnabled(ctx)
}
func (w *MonitoredServiceAndInviter) CreateUserExternalPrincipal(ctx context.Context, userID string, principalID string) error {
	const op = "create_user_external_principal"
	start := time.Now()

	r0 := w.Wrapped.CreateUserExternalPrincipal(ctx, userID, principalID)
	w.Observe(op, time.Since(start), r0 == nil)
	return r0
}
func (w *MonitoredServiceAndInviter) DeleteUserExternalPrincipal(ctx context.Context, userID string, principalID string) error {
	const op = "delete_user_external_principal"
	start := time.Now()

	r0 := w.Wrapped.DeleteUserExternalPrincipal(ctx, userID, principalID)
	w.Observe(op, time.Since(start), r0 == nil)
	return r0
}
func (w *MonitoredServiceAndInviter) GetExternalPrincipal(ctx context.Context, principalID string) (*model.ExternalPrincipal, error) {
	const op = "get_external_principal"
	start := time.Now()

	r0, r1 := w.Wrapped.GetExternalPrincipal(ctx, principalID)
	w.Observe(op, time.Since(start), r1 == nil)
	return r0, r1
}
func (w *MonitoredServiceAndInviter) ListUserExternalPrincipals(ctx context.Context, userID string, params *model.PaginationParams) ([]*model.ExternalPrincipal, *model.Paginator, error) {
	const op = "list_user_external_principals"
	start := time.Now()

	r0, r1, r2 := w.Wrapped.ListUserExternalPrincipals(ctx, userID, params)
	w.Observe(op, time.Since(start), r2 == nil)
	return r0, r1, r2
}
func (w *MonitoredServiceAndInviter) CreateCredentials(ctx context.Context, username string) (*model.Credential, error) {
	const op = "create_credentials"
	start := time.Now()

	r0, r1 := w.Wrapped.CreateCredentials(ctx, username)
	w.Observe(op, time.Since(start), r1 == nil)
	return r0, r1
}
func (w *MonitoredServiceAndInviter) Authorize(ctx context.Context, req *AuthorizationRequest) (*AuthorizationResponse, error) {
	const op = "authorize"
	start := time.Now()

	r0, r1 := w.Wrapped.Authorize(ctx, req)
	w.Observe(op, time.Since(start), r1 == nil)
	return r0, r1
}
func (w *MonitoredServiceAndInviter) InviteUser(ctx context.Context, email string) error {
	const op = "invite_user"
	start := time.Now()

	r0 := w.Wrapped.InviteUser(ctx, email)
	w.Observe(op, time.Since(start), r0 == nil)
	return r0
}
