#!/bin/bash -e
REGISTRY=977611293394.dkr.ecr.us-east-1.amazonaws.com

usage() { 
    echo "Build and publish docker images for lakefs and lakectl based on our published docker image"
    echo "Usage: $0 -v <version> [-l]"
    echo "  -v <version>     docker tag version used to pull the release to publish"
    echo "  -l               tag the release also as latest"
    exit 1;
}

publish() {
    local name=$1
    local version=$2
    local latest=$3

    local aws_img=${REGISTRY}/${name}:${version}

    echo "==> Pull image from ECR - ${aws_img}"
    docker pull ${aws_img}

    echo "==> Tag ${version} and push ${name} to docker hub"
    docker tag ${aws_img} treeverse/${name}:${version}
    docker push treeverse/${name}:${version}

    if [ ${latest} -eq 1 ]; then
        echo "==> Tag latest and push ${name} to docker hub"
        docker tag ${aws_img} treeverse/${name}:latest
        docker push treeverse/${name}:latest
    fi
}

LATEST=0
VERSION=
while getopts ":lv:" o; do
    case "${o}" in
        l)
            LATEST=1
            ;;
        v)
            VERSION=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${VERSION}" ]; then
    echo "version is required!"

    usage
fi

echo "==> Docker login using your ECR"
aws ecr get-login-password | docker login -u AWS --password-stdin $REGISTRY

publish lakefs ${VERSION} ${LATEST}
publish lakectl ${VERSION} ${LATEST}

