import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import compat from 'eslint-plugin-compat';
import prettier from 'eslint-plugin-prettier';
import eslintConfigPrettier from 'eslint-config-prettier';

const browserGlobals = {
  process: 'readonly',
  window: 'readonly',
  document: 'readonly',
  navigator: 'readonly',
  setTimeout: 'readonly',
  setInterval: 'readonly',
  clearTimeout: 'readonly',
  clearInterval: 'readonly',
  localStorage: 'readonly',
  sessionStorage: 'readonly',
  fetch: 'readonly',
  Headers: 'readonly',
  Request: 'readonly',
  Response: 'readonly',
  URLSearchParams: 'readonly',
  XMLHttpRequest: 'readonly',
  FormData: 'readonly',
  Blob: 'readonly',
  File: 'readonly',
  FileReader: 'readonly',
  FileList: 'readonly',
  console: 'readonly',
  alert: 'readonly',
  confirm: 'readonly',
  prompt: 'readonly',
  location: 'readonly',
  history: 'readonly',
  JSON: 'readonly',
  Array: 'readonly',
  ArrayBuffer: 'readonly',
  Boolean: 'readonly',
  DataView: 'readonly',
  Date: 'readonly',
  Error: 'readonly',
  EvalError: 'readonly',
  Function: 'readonly',
  Infinity: 'readonly',
  Int8Array: 'readonly',
  Int16Array: 'readonly',
  Int32Array: 'readonly',
  Intl: 'readonly',
  Map: 'readonly',
  Math: 'readonly',
  NaN: 'readonly',
  Number: 'readonly',
  Object: 'readonly',
  Promise: 'readonly',
  Proxy: 'readonly',
  RangeError: 'readonly',
  ReferenceError: 'readonly',
  Reflect: 'readonly',
  RegExp: 'readonly',
  Set: 'readonly',
  String: 'readonly',
  Symbol: 'readonly',
  SyntaxError: 'readonly',
  TypeError: 'readonly',
  TypedArray: 'readonly',
  URIError: 'readonly',
  Uint8Array: 'readonly',
  Uint8ClampedArray: 'readonly',
  Uint16Array: 'readonly',
  Uint32Array: 'readonly',
  WeakMap: 'readonly',
  WeakSet: 'readonly',
  decodeURI: 'readonly',
  decodeURIComponent: 'readonly',
  encodeURI: 'readonly',
  encodeURIComponent: 'readonly',
  escape: 'readonly',
  eval: 'readonly',
  isFinite: 'readonly',
  isNaN: 'readonly',
  parseFloat: 'readonly',
  parseInt: 'readonly',
  unescape: 'readonly',
  clearInterval: 'readonly',
  setInterval: 'readonly',
  setImmediate: 'readonly',
  clearImmediate: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  DOMException: 'readonly',
  AbortController: 'readonly',
  AbortSignal: 'readonly',
  ResizeObserver: 'readonly',
  IntersectionObserver: 'readonly',
  MutationObserver: 'readonly',
  PerformanceObserver: 'readonly',
};

export default [
  {
    ignores: ['node_modules', 'dist', 'pub'],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{js,jsx,ts,tsx}'],
    plugins: {
      '@typescript-eslint': tseslint.plugin,
      react,
      'react-hooks': reactHooks,
      compat,
      prettier,
    },
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: browserGlobals,
    },
    settings: {
      react: {
        version: 'detect',
      },
    },
    rules: {
      'no-console': 'error',
      'eqeqeq': 'warn',
      'strict': 'error',
      'react/prop-types': 0,
      'react/jsx-key': 0,
      'react/display-name': 0,
      'react/react-in-jsx-scope': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          caughtErrors: 'none',
        },
      ],
      '@typescript-eslint/no-unused-expressions': [
        'error',
        {
          allowShortCircuit: true,
          allowTernary: true,
        },
      ],
      'react-hooks/exhaustive-deps': [
        'error',
        {
          additionalHooks: '(useAPI|useAPIWithPagination)',
        },
      ],
    },
  },
  eslintConfigPrettier,
];
