# coding: utf-8

"""
    lakeFS API

    lakeFS HTTP API

    The version of the OpenAPI document: 0.1.0
    Contact: services@treeverse.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel
from lakefs_sdk.models.import_pagination import ImportPagination
from lakefs_sdk.models.range_metadata import RangeMetadata

class IngestRangeCreationResponse(BaseModel):
    """
    IngestRangeCreationResponse
    """
    range: Optional[RangeMetadata] = None
    pagination: Optional[ImportPagination] = None
    __properties = ["range", "pagination"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> IngestRangeCreationResponse:
        """Create an instance of IngestRangeCreationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of range
        if self.range:
            _dict['range'] = self.range.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pagination
        if self.pagination:
            _dict['pagination'] = self.pagination.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> IngestRangeCreationResponse:
        """Create an instance of IngestRangeCreationResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return IngestRangeCreationResponse.parse_obj(obj)

        _obj = IngestRangeCreationResponse.parse_obj({
            "range": RangeMetadata.from_dict(obj.get("range")) if obj.get("range") is not None else None,
            "pagination": ImportPagination.from_dict(obj.get("pagination")) if obj.get("pagination") is not None else None
        })
        return _obj


