/*
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.lakefs.clients.api;

import io.lakefs.clients.api.ApiException;
import io.lakefs.clients.api.model.Error;
import io.lakefs.clients.api.model.ImportCreation;
import io.lakefs.clients.api.model.ImportCreationResponse;
import io.lakefs.clients.api.model.ImportStatus;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ImportApi
 */
@Ignore
public class ImportApiTest {

    private final ImportApi api = new ImportApi();

    
    /**
     * cancel ongoing import
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void importCancelTest() throws ApiException {
        String repository = null;
        String branch = null;
        String id = null;
                api.importCancel(repository, branch, id);
        // TODO: test validations
    }
    
    /**
     * import data from object store
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void importStartTest() throws ApiException {
        String repository = null;
        String branch = null;
        ImportCreation importCreation = null;
                ImportCreationResponse response = api.importStart(repository, branch, importCreation);
        // TODO: test validations
    }
    
    /**
     * get import status
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void importStatusTest() throws ApiException {
        String repository = null;
        String branch = null;
        String id = null;
                ImportStatus response = api.importStatus(repository, branch, id);
        // TODO: test validations
    }
    
}
