DROP TABLE IF EXISTS multipart_uploads;
DROP INDEX IF EXISTS idx_workspace_entries_parent_path;
DROP TABLE IF EXISTS workspace_entries;
DROP TABLE IF EXISTS branches;
DROP TABLE IF EXISTS commits;
DROP TABLE IF EXISTS entries;
DROP TABLE IF EXISTS object_dedup;
DROP TABLE IF EXISTS objects;
DROP TABLE IF EXISTS repositories;
