  %%{init: { 'theme': 'base', 'gitGraph': {'rotateCommitLabel': true}} }%%
  gitGraph
	  commit id: "2022-02-27 🚮"
	  commit id: "2022-03-01 🚮"
	  commit id: "2022-03-09"
  branch dev
  checkout main
	  commit id: "2022-03-12"
  checkout dev
	  commit id: "d: 2022-03-14 🚮"
	  commit id: "d: 2022-03-16 🚮"
  checkout main
	  commit id: "2022-03-18"
  checkout dev
	  commit id: "d: 2022-03-20 🚮"
	  commit id: "d: 2022-03-23"
  checkout main
  merge dev
	  commit id: "2022-03-26"
