BEGIN;
CREATE TABLE IF NOT EXISTS staging_kv
(
    staging_token varchar not null,
    key bytea not null,
    identity bytea not null,
    data bytea
) PARTITION BY HASH (staging_token);
CREATE TABLE IF NOT EXISTS staging_kv_p0 PARTITION OF staging_kv FOR VALUES WITH (MODULUS 10, REMAINDER 0);
CREATE TABLE IF NOT EXISTS staging_kv_p1 PARTITION OF staging_kv FOR VALUES WITH (MODULUS 10, REMAINDER 1);
CREATE TABLE IF NOT EXISTS staging_kv_p2 PARTITION OF staging_kv FOR VALUES WITH (MODULUS 10, REMAINDER 2);
CREATE TABLE IF NOT EXISTS staging_kv_p3 PARTITION OF staging_kv FOR VALUES WITH (MODULUS 10, REMAINDER 3);
CREATE TABLE IF NOT EXISTS staging_kv_p4 PARTITION OF staging_kv FOR VALUES WITH (MODULUS 10, REMAINDER 4);
CREATE TABLE IF NOT EXISTS staging_kv_p5 PARTITION OF staging_kv FOR VALUES WITH (MODULUS 10, REMAINDER 5);
CREATE TABLE IF NOT EXISTS staging_kv_p6 PARTITION OF staging_kv FOR VALUES WITH (MODULUS 10, REMAINDER 6);
CREATE TABLE IF NOT EXISTS staging_kv_p7 PARTITION OF staging_kv FOR VALUES WITH (MODULUS 10, REMAINDER 7);
CREATE TABLE IF NOT EXISTS staging_kv_p8 PARTITION OF staging_kv FOR VALUES WITH (MODULUS 10, REMAINDER 8);
CREATE TABLE IF NOT EXISTS staging_kv_p9 PARTITION OF staging_kv FOR VALUES WITH (MODULUS 10, REMAINDER 9);

CREATE UNIQUE index staging_kv_uidx
    on staging_kv (staging_token asc, key asc);
COMMIT;
