DROP TABLE IF EXISTS catalog_auth_credentials;
DROP TABLE IF EXISTS catalog_auth_group_policies;
DROP TABLE IF EXISTS catalog_auth_user_policies;
DROP TABLE IF EXISTS catalog_auth_user_groups;
DROP TABLE IF EXISTS catalog_auth_policies;
DROP TABLE IF EXISTS catalog_auth_groups;
DROP TABLE IF EXISTS catalog_auth_users;
DROP TABLE IF EXISTS catalog_auth_account_metadata;

SET CONSTRAINTS catalog_repositories_branches_id_fk DEFERRED;
DROP TABLE IF EXISTS catalog_repositories;
DROP TABLE IF EXISTS catalog_object_dedup;
DROP TABLE IF EXISTS catalog_multipart_uploads;
DROP TABLE IF EXISTS catalog_lineage;
DROP TABLE IF EXISTS catalog_entries;
DROP TABLE IF EXISTS catalog_commits;
DROP TABLE IF EXISTS catalog_branches;
DROP TYPE IF EXISTS catalog_merge_type;
DROP TYPE IF EXISTS catalog_commit_status;
DROP VIEW IF EXISTS catalog_entries_v;
DROP SEQUENCE IF EXISTS catalog_repositories_id_seq;
DROP SEQUENCE IF EXISTS catalog_branches_id_seq;
