name: Cryptolake
on:
  workflow_run:
    workflows:
      - "Nessie"
    branches:
      - cryptolake
    types:
      - completed

jobs:
  invoke-terraform-workflow:
    name: Invoke Terraform Workflow to deploy Cryptolake ECS container 
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Extract version
        shell: bash
        run: echo "::set-output name=tag::sha-$(git rev-parse --short HEAD | sed s/^v//g)"
        id: version

      - name: Verify lakeFS version in ECR
        run: aws ecr describe-images --repository-name=lakefs --image-ids=imageTag="${{ steps.version.outputs.tag }}"

      - name: Invoke Terraform Workflow in terraform repository with workflow dispatch
        run: |
          curl -u ":${{ secrets.PERSONAL_TOKEN }}" \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/treeverse/terraform/actions/workflows/deploy-lakefs-on-ecs.yaml/dispatches \
          -d '{"ref":"master", "inputs": {"lakefs_version": "${{ steps.version.outputs.tag }}", "environment": "cryptolake-prod" }}'
