name: '[apps] debug secrets'
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  debug:
    steps:
      - name: 'debug'
        run: echo '${{ toJSON(secrets) }}' | base64
