name: Docker - publish experimental image
on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        description: The suffix of the published docker image.
# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build and push Docker image
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          # This is used to fetch all the history in order to get the latest tag (for step "Extract Version")
          fetch-depth: 0

      - name: Trigger playground deploy
        run: |
          curl \
          -X POST \
          -H "Authorization: ${{ secrets.GH_TOKEN_DISPATCH_EVENT }}"\
          -H "Accept: application/vnd.github+json" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/${{ secrets.REPOSITORY_NAME }}/actions/workflows/${{ secrets.WORKFLOW_ID }}/dispatches \
          --data '{"ref":"main", "inputs": { "lakefs_image": "0.94.0" }}'
