name: documentation release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "specific version to publish"

jobs:
  docs-release:
    name: Documentation release
    runs-on: ubuntu-20.04
    steps:
      - name: Check-out
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.79.0
        with:
          working-directory: docs
          ruby-version: 2.6
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Extract version
        id: version
        shell: bash
        run: |
          if [ "${{ github.event.inputs.tag }}" != "" ]; then
            echo "tag=$(echo ${{ github.event.inputs.tag }} | cut -d. -f1-2)" >> $GITHUB_OUTPUT
          else
            echo "tag=$(echo ${GITHUB_REF##*/} | cut -d. -f1-2)" >> $GITHUB_OUTPUT
          fi

      - name: Build release
        working-directory: docs
        run: bundle exec jekyll build --config _config.yml -d _site/${{ steps.version.outputs.tag }} -b /${{ steps.version.outputs.tag }}

      - name: Update published version
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_TOKEN }}
        run: >
            curl -s https://${API_TOKEN_GITHUB}@raw.githubusercontent.com/treeverse/docs-lakeFS/main/versions.json |
            jq '."${{ steps.version.outputs.tag}}" = "${{ steps.version.outputs.tag}}"' > docs/_site/versions.json

      - name: Publish to docs repository
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_TOKEN }}
        with:
          source_file: docs/_site/.
          destination_repo: treeverse/docs-lakeFS
          destination_folder: /
          user_email: 'support@treeverse.io'
          user_name: 'nopcoder'

