name: documentation test

on:
  pull_request:

jobs:
  docs-release:
    name: Documentation release
    runs-on: ubuntu-20.04
    steps:
      - name: Check-out
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: docs
          ruby-version: '2.6'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Extract version
        id: version
        shell: bash
        run: echo "tag=v0.102.0" >> $GITHUB_OUTPUT

      - name: Build release
        working-directory: docs
        run: bundle exec jekyll build --config _config.yml -d _site/${{ steps.version.outputs.tag }} -b /${{ steps.version.outputs.tag }}

      - name: Publish to lakeFS-docs repository
        env:
          SSH_DEPLOY_KEY: '${{ secrets.SSH_LAKEFS_DOCS_DEPLOY_KEY }}'
          SOURCE_DIRECTORY: 'docs/_site/'
          TARGET_DIRECTORY: ''
          GIT_CMD_REPOSITORY: 'git@github.com:treeverse/docs-test.git'
          USER_EMAIL: 'support@treeverse.io'
          USER_NAME: 'docs-action'
          TARGET_BRANCH: 'main'
        shell: bash
        run: ./.github/scripts/push-repo.sh
