name: documentation test

on:
  pull_request:

jobs:
  docs-release:
    name: Documentation release
    runs-on: ubuntu-20.04
    steps:
      - name: Check-out
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: docs
          ruby-version: '2.6'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Extract version
        id: version
        shell: bash
        run: echo "tag=v0.101.0" >> $GITHUB_OUTPUT

      - name: Build release
        working-directory: docs
        run: bundle exec jekyll build --config _config.yml -d _site/${{ steps.version.outputs.tag }} -b /${{ steps.version.outputs.tag }}

      - name: Push generated docs to lakeFS-docs repository
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_LAKEFS_DOCS_DEPLOY_KEY }}
        with:
          source-directory: docs/_site/
          destination-github-username: docs-action
          #destination-repository-name: treeverse/docs-lakeFS
          destination-repository-name: treeverse/docs-test
          user-email: support@treeverse.io

