name: documentation

on:
  push:
    paths:
      - "docs/**"
    branches:
      - master
      - feature/docs-versions
  workflow_dispatch:
    inputs:
      tag:
        description: "specific version to publish"

jobs:
  lakefs-hadoopfs:
    name: Build documentation
    runs-on: ubuntu-20.04
    steps:
      - name: Check-out
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.79.0
        with:
          working-directory: docs
          ruby-version: 2.6
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Build
        #if: github.ref == 'refs/heads/master'
        working-directory: docs
        run: bundle exec jekyll build --config _config.yml,_config.master.yml -d _site/ -b /docs-lakeFS

      - name: Push
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_TOKEN }}
        with:
          source-directory: docs/_site
          destination-github-username: treeverse
          destination-repository-name: docs-lakeFS
          user-email: barak.amar@treeverse.io
          target-branch: main

      # build specific version exclude version.json
      #- name: Build specific version
        #uses: helaili/jekyll-build@v2
        #if: startsWith(github.ref, 'refs/tags/v')
        #with:
            #target_branch: gh-pages
            #target_path: /
            #keep_history: true
            #token: ${{ secrets.GITHUB_TOKEN }}
