name: documentation

on:
  push:
    paths:
      - "docs/**"
    branches:
      - master
      - feature/docs-versions
  workflow_dispatch:
    inputs:
      tag:
        description: "specific version to publish"

jobs:
  lakefs-hadoopfs:
    name: Build documentation
    runs-on: ubuntu-20.04
    steps:
      - name: Check-out
        uses: actions/checkout@v2

      - name: Build
        uses: helaili/jekyll-action@v2
        #if: github.ref == 'refs/heads/master'
        with:
          jekyll_build_options: "--config _config.yml,_config.master.yml -b /"
          jekyll_src: docs
          build_only: true
    
      - name: Push documentation
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_TOKEN }}
        with:
          source-directory: jekyll_build
          destination-github-username: treeverse
          destination-repository-name: docs-lakeFS
          user-email: barak.amar@treeverse.io
          target-branch: main

      # build specific version exclude version.json
      #- name: Build specific version
        #uses: helaili/jekyll-build@v2
        #if: startsWith(github.ref, 'refs/tags/v')
        #with:
            #target_branch: gh-pages
            #target_path: /
            #keep_history: true
            #token: ${{ secrets.GITHUB_TOKEN }}
