/*
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.lakefs.clients.sdk.model;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ChecksumAlgorithm
 */
public class ChecksumAlgorithmTest {
    /**
     * Model tests for ChecksumAlgorithm
     */
    @Test
    public void testChecksumAlgorithm() {
        // TODO: test ChecksumAlgorithm
    }

}
