/*
 * lakeFS API
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.lakefs.clients.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.lakefs.clients.sdk.model.LocalTable;
import io.lakefs.clients.sdk.model.RemoteTable;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IcebergPushRequest
 */
public class IcebergPushRequestTest {
    private final IcebergPushRequest model = new IcebergPushRequest();

    /**
     * Model tests for IcebergPushRequest
     */
    @Test
    public void testIcebergPushRequest() {
        // TODO: test IcebergPushRequest
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'destination'
     */
    @Test
    public void destinationTest() {
        // TODO: test destination
    }

    /**
     * Test the property 'forceUpdate'
     */
    @Test
    public void forceUpdateTest() {
        // TODO: test forceUpdate
    }

    /**
     * Test the property 'createNamespace'
     */
    @Test
    public void createNamespaceTest() {
        // TODO: test createNamespace
    }

}
